### ISSUE TITLE
Discussion: where and how to serve the volve data

### ISSUE THREAD

**Issue by Brynjulf** [equinor/esv-intersection#275]
The current implementation of fetching data directly from GitHub is less than ideal because of the low request limit (60 requests/hour) is easily reached.

One possible way to go would be to create a small api that we communicate with that caches the data

Continuation on #140

**Comment by Brynjulf** [comment]
@andreabrambilla will investigate if we can put the volve data in this repo along with the storybook code so that we can avoid a lot of head ache and always serve the same data

**Comment by andreabrambilla** [comment]
Not a super-reliable source but let's keep it in mind: https://softwareengineering.stackexchange.com/questions/264968/can-a-single-github-repository-include-source-code-released-under-multiple-licen

I have asked Thorvald, waiting for comments. 

All in all, it's probably possible. I still wonder if we should do it or not. It would be definitely cleaner to have only one license per repo. There are also automatic scanner that looks for license issues, and having mixed licenses would definitely be a problem for such scanners.

Maybe a way to drag in the data from the separate repo could be to make the `esv-intersection-data` repository a sub-module of the `esv-intersection` repo
(sub-module are not one of the nicest features of git, but since the data repo will not change much, it should be manageable)

**Comment by andreabrambilla** [comment]
TODO: ask radix team if submodules are supported

**Comment by andreabrambilla** [comment]
NOTE: this is related to #265

**Comment by andreabrambilla** [comment]
I have started trying out the submodule solution, but before making a pr here, I need to have this merged first https://github.com/equinor/esv-intersection-data/pull/5

**Comment by HavardNJ** [comment]
Just googled a bit and it seems it's possible to run git commands in a dockerfile. If so we could simply clone the data from the seperate repo. I'm not sure if git will have online access in radix, npm install works but they may have opened up for this specifically.
