### ISSUE TITLE
Document input data format

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#308]
For every layer and for all the "main"classes (reference system, controller, etc)

**Comment by schoening** [comment]
**Closed an issue, adding it as a comment here:**
Create a Storybook entry with data from POZO#328
Håvard and I have the intersection.json file to try this out.
Note that the file cannot be published because the data is confidential, we would have to create an analogous file for showing this in the public storybook

**Comment by schoening** [comment]
Closing. We are continuously improving the input data types.
