### ISSUE TITLE
Label on fault lines disappears. Might be related to leftToRight bug

### ISSUE THREAD

**Issue by ooystein** [equinor/esv-intersection#413]
Description from Tone Berit:

Example is from POZO on D-41 well on Johan Sverdrup

Ref picks and prognosed picks text is overlapping Formation text and Group text.

The intersection view is for reporting purposes used to create the right overview picture of a well compared to the depth model. Some illustrations are overview focused (zoomed out) and other pictures needs to be more close up. Overlapping of labels should be avoided. It makes it difficult to interpret the image.

![image001](https://user-images.githubusercontent.com/705469/102595633-33dbde80-4118-11eb-8de2-a715e629890c.jpg)
![image002](https://user-images.githubusercontent.com/705469/102595632-33434800-4118-11eb-936a-dfc8da09e98c.jpg)

**Comment by HavardNJ** [comment]
If we have surface names such as "Eiriksson Fm. 2 JS (STATFJORD GP. Top to Eriksson FM. 2 JS)", it's going to take alot of screen real estate and will be very hard to not get any overlap. Label layout is complex, but we might be able to solve it by putting all labels on one layer or data structure and use a force system for label placement. Might be hard to tune ideally since we have some labels that should not move (or move along a specific path like formation labels) and some that can move more freely like picks labels. Might need to take into concern that the lines from picks may overlap other labels as well.

**Comment by ooystein** [comment]
The apps consuming this library can let the users turn on/off the different layers if the user has problems with reading labels. Closing this issues.
